services:
  - type: web
    name: aichatbot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT chatbot:app
    envVars:
      - key: GROQ_API_KEY
        value: your_api_key_here
